version: "2.1"

services:
  app:
    build: .
    ports:
      - "9091:9090"
    volumes:
      - .:/app
    depends_on:
      - mysql-db
    env_file:
      - ./vars.env

  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=example_password
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=example_user
      - MYSQL_PASSWORD=example_password
    volumes:
      - db_data:/var/lib/mysql
   
volumes:
  db_data:
